### ISSUE TITLE
古いCIをキャンセルさせたい

### ISSUE THREAD

**Issue by tochiman** [tochiman/brain-quoridor#28]
Workflowが溜まっていかないように、新たにCIが作成されたら実行途中のCIをキャンセルすること

**Comment by tochiman** [comment]
対策方法
```yaml
      # 現在動いているワークフローをキャンセル
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
   ```
