### ISSUE TITLE
古いCIが削除されない問題

### ISSUE THREAD

**Issue by tochiman** [tochiman/brain-quoridor#31]
concurrencyで対処する必要があることを確認。
```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
```
